#include <iostream>
using namespace std;

struct MyException{
	const char* test() const throw(){
		return "MY ERROR";
	}
};

double division(double a, double b){
    if (a !=0 && b == 0) {
        throw "Zero Division error"; }
        else if (b == 3) {
            throw "An error occured";
        }
        else if (a == 0 && b == 0){
            throw 404;
        } return a/b;
}    
int main() {
    try { 
        int num1 = 0, num2 = 0;
        division (num1,num2);
    }
    catch (const char* msg) { 
        cout << msg << endl;
    }
    catch (int x){
        cout << x << endl;
    }
    catch (MyException & e){
    	cout << e.test() << endl;
	}
    return 0;
}
